### ISSUE TITLE
RuntimeError: The size of tensor a (80) must match the size of tensor b (44) at non-singleton dimension 3

### ISSUE THREAD

**Issue by lijunyu159** [lmomoy/LF-YOLO#3]
Hi, when I run `python detect.py --source data/images --weights LF-YOLO.pt --conf 0.25`, I find there is no LF-YOLO.pt and I use yolov3.pt instead, but I get an error: `RuntimeError: The size of tensor a (80) must match the size of tensor b (44) at non-singleton dimension 3`. Could you help me? Thank you!

**Comment by lmomoy** [comment]
You need to train your .pt file. In addition, Where did you get the yolov3.pt file?

**Comment by lijunyu159** [comment]
> You need to train your .pt file. In addition, Where did you get the yolov3.pt file?

Thank you for your replying! Due to the time, I only trained for less than 10 epochs under the COCO dataset, and I got my .pt file. Unfortunately, when I run detect.py to inference/images/zidane.jpg using this weight, I get an image without any bounding box and predicting results i.e. original image. I think the reason is my weights. So could you contribute your LF-Yolo.pt? Thank you!
